version: '2'
services:
  angular-smartui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:80'
    volumes:
      - '/var/log/container-logs:/var/log/container-logs'
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://localhost:514'