# be sure you have an up and running docker swarm cluster (1 node or more):
docker swarm init
# store your API keys using docker secret manager:
echo AccessID | docker secret create sumo-access-id
echo AccessKey | docker secret ceate sumo-access-key

version: '1'

services:
  angular-smartui:
    environment:
      - NODE_ENV=development
      - PORT=80
      - DB_AUTHENTICATE=false
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: angular-smartui
    ports:
      - '9000:80'
    networks:
      - node-network

  sumologic:
    image: sumologic/collector:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
    secrets:
      - sumo-access-id
      - sumo-access-key
    environment:
      SUMO_ACCESS_ID_FILE: /run/secrets/sumo-access-id
      SUMO_ACCESS_KEY_FILE: /run/secrets/sumo-access-key

secrets:
  sumo-access-id:
    external: true
  sumo-access-key:
    external: true
networks:
  node-network:
    driver: bridge
